on:
  push:
    tags:
      - dev-v*
jobs:
  deploy-dev:
    name: deploy dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm install -g yarn

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn export

      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: s0/git-publish-subdir-action@develop
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
