on:
  push:
    tags:
      - dev-v*
env:
  ENVIROMENT_SLUG: production
  NEXT_PUBLIC_SUPA_BASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPA_BASE_ANON_KEY }}
  NEXT_PUBLIC_FORM_API: ${{ secrets.NEXT_PUBLIC_FORM_API }}
jobs:
  deploy-dev:
    name: deploy dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm install -g yarn

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn postbuild
          yarn export

      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: hostinger-dev
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
