name: Deploy to GitHub Pages
on:
  push:
    branches:
      - dev
jobs:
  deploy-dev:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16
          cache: npm

      - run: npm install -g yarn

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn export

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dev
          FOLDER: ./out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
